### ISSUE TITLE
As a developer, I want to store and retrieve my credentials safely so that I can improve security

### ISSUE THREAD

**Issue by CliffordAnderson** [HeardLibrary/cloud-tvnews#3]
- [ ] Set up [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/)
- [ ] Provide sample code to illustrate how to write, edit, and retrieve secrets from AWS Secrets Manager

**Comment by CliffordAnderson** [comment]
@baskaufs We should figure out how to use [AWS Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html) to store our ARNs in JSON configuration files.

**Comment by CliffordAnderson** [comment]
@baskaufs See also [Managing Secrets for Amazon](https://aws.amazon.com/blogs/compute/managing-secrets-for-amazon-ecs-applications-using-parameter-store-and-iam-roles-for-tasks/)

**Comment by CliffordAnderson** [comment]
@baskaufs After reading more about the issue last night, I think we should perhaps just take a simpler approach. If the issue is sharing our AWS Account ID on Github, then maybe the best plan would be to write a regex that we use before checking in code, swapping out the Account ID in the ARN with `<Your Account ID>'. Would that solve the issue?

**Comment by baskaufs** [comment]
At this point, the genie's kinda out of the bottle.  Unless we blow up this repo, the Account ID is going to be in the history forever.  Of course, I'm not sure that anybody would bother looking for it...

**Comment by baskaufs** [comment]
It seems like the solution here isn't to create ARNs that use our account number, but rather to figure out a way to use ARNs that are publicly available.  This could either use canned AWS roles and functions, or by putting our stuff in a publicly accessible repository that isn't based on our account number.  I haven't had time to read and understand it, but I think this page may offer clues:
https://aws.amazon.com/blogs/compute/announcing-nested-applications-for-aws-sam-and-the-aws-serverless-application-repository/

Later comment:  it appears that there are many AWS-managed policies, but very few AWS-managed roles.  That would simplify the process of building roles, since in a lot of cases we wouldn't need to build our own policies.  But it would not get us out of the business of having roles that have our account number built into their ARNs.

**Comment by baskaufs** [comment]
I still don't entirely understand how it works, but apparently when a serverless application is deployed from the AWS Serverless Application Repository, it may create custom IAM roles within the deploying user's account.  See https://docs.aws.amazon.com/serverlessrepo/latest/devguide/acknowledging-application-capabilities.html which discusses the user allowing the Serverless Application Repository to create IAM roles and resource policies as part of the deployment process.  So there must be some way to make the application generic with respect to roles and policies before it is archived in the SAR.

**Comment by baskaufs** [comment]
On a similar vein, the process of configuring an application that is to be deployed from the SAR, there is an "application settings" section (see step 5).  
https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverless-app-consuming-applications.html
At that point in the process, the deployer specifies particular resources that the application has access to, such as DynamoDB tables, S3 buckets, or Gateway APIs.  

So again, in the process of archiving an application in the SAR, there must be some step that involves making generic the resources that are to be accessed by the code.

**Comment by baskaufs** [comment]
These previous comments deal with handling implementation-specific resources at a very high level (making the overall application generic at the time of archiving the entire serverless application).  On a much lower level, if we keep things generic by controlling implementation-specific details during the build process, the IAM policies and roles to be used by the state machines, lambdas, etc. can be built as part.  

See this example:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/iam-example-policies.html
where a policy with a particular name is created using a Python script and a policy attached to a role using a different script.  After they are built, the role can then be attached to a lambda as part of the command line interface (CLI) command that uploads the lambda.

In this scenario, a user avoids the hard-coding issue by just building everything from scratch on the local computer and pushing it up to AWS.  I think pretty much everything can be done using the AWS SDK for Python (boto3), including building the state machine itself.  See 
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions.html

**Comment by baskaufs** [comment]
OK, I have found out how one makes ARNs generic at the serverless application model (SAM) level.  SAM is a way to build serverless applications from lambdas and other resources that work together.  It's a high-level way to specify what should go into the application and the SAM YAML is interpreted by Cloud Formation to actually build the thing.  Within the SAM YAML, you can use `Fn::Sub`, which substitutes values that are provided at run time to be substituted within the SAM document.  Here's the description:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html
One thing that isn't yet clear to me is whether you can actually build state machines with SAM, or only applications that are made from raw lambdas (as opposed to lambdas run by state machines).

**Comment by CliffordAnderson** [comment]
@baskaufs Nice! This looks like exactly what we want as we seek to make our architecture reproducible. Let's chat with the Amazon reps about the relationship to Step Functions/state machines during their visit this week.

**Comment by baskaufs** [comment]
OK, as of two years ago, it does not appear that step functions can be directly integrated with SAM:
https://www.reddit.com/r/aws/comments/5h0ojs/sam_and_step_functions/
I've looked for more recent info like 
https://www.reddit.com/r/aws/comments/b4qbo7/resources_for_step_functions/
but it doesn't look like they've done the integration yet.  According to the older blog post, the way to use a state machine in SAM is to create it as a "custom resource", then use it in Cloud Formation.  I don't entirely understand that, but it sounds like a hack.

It seems like you either build the system using state machines and don't try to describe the system using SAM, or build it using generic lambdas, then build the whole system description using SAM.  I don't think these two approaches are mutually exclusive, since I think you could build the system as state machines, then when it's running in production, build the SAM description of the underlying lambdas for easy deployment elsewhere.

One of the implications of this is that we should build as little logic as possible in the state machines themselves (stuff like conditional executions, loops, etc.) but rather build that directly into the lambdas. Then if we want to dump the state machine system in favor of SAM, we would not have to recode.

**Comment by baskaufs** [comment]
OK, @CliffordAnderson and @jimdur8n, in the process of looking at this issue, I've spun off two new issues (#14 and #13) that I think are relevant to future milestones, but not this first one.  What's left of this issue is related to two things: 
- do we need to keep our account number secret?
- are there other uses of the AWS secrets manager that would require us to figure out how to use it at this point?

I think there are two answers to the first question: 1. It's already not a secret because I've pushed it up to GitHub and there's no way to make it go away permanently nor to change our account number.  2. I don't think that it's necessary anyway.  

The comments I've seen on the web about keeping account numbers secret are mostly along the lines of "well, just to be paranoid, it wouldn't hurt to keep it secret".   The posts that talk about the actual, necessary security procedures (like securing passwords, making sure you don't reveal keys, and using 2FA) don't mention it as a problem, and we are already being careful about those procedures.

Worrying about publishing the account numbers also places a drag on us having a nimble workflow where we constantly have to worry about purging the account number from everything we push to GitHub.  The other side of the issue (now removed to issue #14), making sure that the code is usable by others, can be dealt with in other ways at a later time.  So I don't see any reason to let this issue block us on the first milestone.

As far as the second part of the question is concerned, I don't see any reason why we need to use the secrets manager at this point.  Our keys for accessing the AWS command line interface (CLI) are stored locally on our computer, so that isn't an issue.  The kinds of secret keys that AWS talks about managing with the secrets manager are necessary for servers to talk with each other and we don't really have that.  We just have lambdas that are isolated within our system that can freely pass information among themselves.  We will want to figure out how to use the parameter store, but that's not specifically related to the secrets manager and will probably be part of the next milestone.

So I think this issue should be closed and I'll move on to other things.  If you concur, one of you can close this issue.

**Comment by jimdur8n** [comment]
Hi @baskaufs, @CliffordAnderson I agree, we close this issue and take Steve's advice and not worry about the account number. **BUT** once we're finished with this project, we create a new AWS account for TV News and abandon this current AWS account vu-library-tvnews

That will give as experience with building a new archive and test our replicability. It will give us a clean start removing all the garbage that's in our account already (think Coconut), and we won't have to worry about our account number in the GitHub source code.

**Comment by CliffordAnderson** [comment]
We agreed to leave the ARN in place for the present as not a serious security risk. However, we will create a new story about automating deployment, which will include generating appropriate ARNs for third-party users.
